spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"



  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    #    url: -------------------------------develop 용
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/banjjog
    #    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  logging.level:
    org.hibernate:
      sql: debug
      type.descriptor.sql: trace # sql의 데이터까지 다 보이게

#  redis:
#    #    host: redis ----------------------------- 요건 develop용
#    host: localhost
#    port: 6379


  jackson:
    time-zone: Asia/Seoul

server:
  error:
    include-exception: false     # Response 에 Exception 을 표시할지
    include-message: always      # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
  port: 8083
  forward-headers-strategy: native


cors:
  front_url: "*"

# swagger 관련
springfox:
  documentation:
    swagger:
      use-model-v3: false
